### ISSUE TITLE
snap package does not have a removable-media connection point.

### ISSUE THREAD

**Issue by flord** [afichet/openexr-viewer#38]
It is not possible to load images from anywhere else than the home directory when using the snap package on linux. Normally, we should be able to run this command `sudo snap connect openexr-viewer:removable-media` to add support to the removable media directories, but this snap does not even have the plug for it.

**Comment by afichet** [comment]
Hi,

Thanks for the notice. I am not using snap myself so would not have discovered it without your message.
It shall be fixed now after a `snap refresh`.

Cheers.

**Comment by flord** [comment]
Thanks! It took 24 hours before the update came through, but it works now.
