### ISSUE TITLE
Add framebuffer type

### ISSUE THREAD

**Issue by Kri-Ol** [afichet/openexr-viewer#39]
would be nice to know if dealing with singles of halfs. Maybe just on the same line

framebuffer -> framebuffer of singles (or floats, or halfs)

**Comment by afichet** [comment]
Indeed, that was on my todo list. I am surprise I haven't added to the issues.
Now you're mentioning it, that's the good time to add this feature soon :)

**Comment by afichet** [comment]
It's now on master, I'll make release including this feature next week.

**Comment by Kri-Ol** [comment]
Thank you
