### ISSUE TITLE
Feature Request: Add package to winget

### ISSUE THREAD

**Issue by Andrej730** [afichet/openexr-viewer#40]
So it would be possible to install it with `winget install openexr-viewer` in cmd.
Winget packages github - https://github.com/microsoft/winget-pkgs

**Comment by afichet** [comment]
Hi,

Thanks, this is a great suggestion!

Unfortunately, after submitting the pull request, I noticed that I had to comply with a CLA that seems out of reach for my contribution: I heavily rely on OpenEXR and Qt, and they stipulate that "each of Your Submissions is entirely Your original work": https://github.com/microsoft/winget-pkgs/pull/108450

I have very few hopes they will answer to my concern on this pull request. So, the Windows Installer is still the preferred option for now.

I'll keep this pull request opened until potential further development from the winget repository moderators.

Cheers.

**Comment by afichet** [comment]
Quick update, I've got the confirmation on the PR the CLA applies only to the manifest file.

So, the package is waiting for a second review to be available through winget. I guess that's a matter of weeks.

I'll close the issue when the PR will be merged and update the README.md to give the instructions to install OpenEXR Viewer through this channel.

Thanks again for this suggestion!

**Comment by afichet** [comment]
This software is now available threw winget with:
```
winget install openexr-viewer
```
