### ISSUE TITLE
Vulnerability in openexr-viewer

### ISSUE THREAD

**Issue by GAP-dev** [afichet/openexr-viewer#43]
Hello,
I found vulnerability in openexr-viewer.
Where can i report this?

**Comment by GAP-dev** [comment]
oh, I will check now.

**Comment by GAP-dev** [comment]
It seems perfect!
I would like to submit a CVE request.

**Comment by afichet** [comment]
Thanks a lot for your issue and your help! Currently pushing the updated version.

Regarding the CVE request, I am not familiar with this process. Does this require action on my end?

**Comment by GAP-dev** [comment]
The best way is to enable security.md in github.
If you enable security.md, I will report again through github security advisory.
<img width="1153" alt="Screenshot 2023-12-10 at 10 32 11 AM" src="https://github.com/afichet/openexr-viewer/assets/73922876/dc79cb60-8b44-4304-8f1b-e8fdcf773969">

**Comment by afichet** [comment]
Thanks for the screenshot!
I've approved the request and the review for a CVE.
Let me know if there is additional action needed from my part. I'll reopen the issue if that's the case.
Cheers.
